### PR TITLE
Use flags for config:set

### LINKED ISSUE #34: Unable to set config using flags
The [docs](https://github.com/DMeechan/stream-cli/blob/master/docs/config.md) mention that the `stream config:set` command should work with the following flags:

```
OPTIONS
  -e, --email=email    Email for configuration.
  -j, --json           Output results in JSON. When not specified, returns output in a human friendly format.
  -k, --key=key        API key for configuration.
  -m, --mode=mode      Environment to run in (production or development for token and permission checking).
  -n, --name=name      Full name for configuration.
  -s, --secret=secret  API secret for configuration.
  -t, --telemetry      Enable error reporting for debugging purposes.
  -u, --url=url        API base URL for configuration.
```

But regardless of how I call it, the command ignores the flags and instead prompts for them individually:

```bash
$ stream config:set --name "name" --email "email" --key "key" --secret "secret" --url "url"
? What is your full name? ›
```
```bash
$ stream config:set --name=name --email=email --key=key --secret=secret --url=url
? What is your full name? ›
```
```bash
stream config:set -n name -e email -k key -s secret -u url
? What is your full name? ›
```

Using version: `getstream-cli/0.0.61 darwin-x64 node-v12.10.0`

### PR DESCRIPTION
**Pull request by DMeechan**
Fixes #34:

1. Renamed `mode` (`m`) flag to `environment` (`v`) to match what the prompt expects. Am happy to use a different letter here if preferred
2. Writing the config would fail when the (optional) `telemetry` flag wasn't provided. Added a default value of `true` (because the prompt defaults to true)

### CODE REVIEW

**Comment by giautm** [comment]
Hi @DMeechan, why this PR revert the changes from https://github.com/GetStream/stream-cli/pull/30 ?

**Comment by ferhatelmas** [comment]
@giautm it seems #30 was done in build folder, not in source folder. 

@nparsons08 @thesyncim is the functionality in #30 needed ?

**Comment by giautm** [comment]
Currently, Is there no command for listing members of a channel?

**Comment by ferhatelmas** [comment]
@giautm functionality is added back in [0.1.1](https://www.npmjs.com/package/getstream-cli/v/0.1.1)

**Pull request merged**
